# Generated by Django 4.0.6 on 2022-07-17 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_newlistingform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewListingForm',
            new_name='NewListingModel',
        ),
    ]
