# Generated by Django 4.0.6 on 2022-07-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_newlistingform_newlistingmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewListingModel',
            new_name='Listing',
        ),
    ]
