# Generated by Django 4.0.6 on 2022-07-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_newlistingmodel_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
