# Generated by Django 4.0.6 on 2022-07-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='start_date',
            field=models.DateField(auto_now_add=True, default='2022-07-20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
