# Generated by Django 4.0.6 on 2022-07-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_start_date_alter_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='end_date',
            field=models.DateField(default='2022-07-21'),
            preserve_default=False,
        ),
    ]
