# Generated by Django 4.0.6 on 2022-07-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='item_image',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
    ]
