# Generated by Django 4.0.6 on 2022-07-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='item_image',
            field=models.ImageField(blank=True, default='', upload_to='uploads /'),
        ),
    ]
