# Generated by Django 4.0.6 on 2022-07-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listing_end_date_alter_listing_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
