# Generated by Django 4.0.6 on 2022-07-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listing_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='item_image',
            field=models.ImageField(blank=True, upload_to='uploads /'),
        ),
    ]
