# Generated by Django 4.0.6 on 2022-07-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_listing_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
