# Generated by Django 4.0.6 on 2022-08-20 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_listing_owner_delete_watcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watched_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
