# Generated by Django 4.0.6 on 2022-07-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_listing_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
