# Generated by Django 4.0.6 on 2022-08-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_remove_comment_owner_alter_listing_owner_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
    ]
