# Generated by Django 4.0.6 on 2022-08-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_remove_listing_price_listing_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='initial_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
